### ISSUE TITLE
Version 0.28.6 not working on linux_amd64

### ISSUE THREAD

**Issue by daniepett** [chanzuckerberg/terraform-provider-snowflake#927]
**Provider Version**

0.28.6
linux_amd64

**Terraform Version**

1.1.7

**Describe the bug**

Go throwing errors during terraform plan using the linux_amd64 version of the provider, running locally using darwin_amd64 it is working as expected

**Code samples and commands**

```
Stack trace from the terraform-provider-snowflake_v0.28.6 plugin:
panic: time: missing Location in call to Time.In
goroutine 44 [running]:
time.Time.In(...)
	time/time.go:1106
github.com/snowflakedb/gosnowflake.stringToValue(0xc000637cb0, {{0xc000484300, 0xa}, 0x0, 0x0, {0xc000484310, 0xd}, 0x0, 0x3, 0x1}, ...)
	github.com/snowflakedb/gosnowflake@v1.6.7/converter.go:227 +0xe06
github.com/snowflakedb/gosnowflake.(*snowflakeRows).Next(0xc0002de540, {0xc000637cb0, 0x9, 0xd})
	github.com/snowflakedb/gosnowflake@v1.6.7/rows.go:173 +0x4b6
github.com/luna-duclos/instrumentedsql.wrappedRows.Next({{{0x139b020, 0xc00037cf50}, {0x139b080, 0x1bb5578}, 0x0, 0x0}, {0x13be610, 0xc0000cc020}, {0x13aad58, 0xc0002de540}}, ...)
	github.com/luna-duclos/instrumentedsql@v1.1.3/rows.go:52 +0x1e2
database/sql.(*Rows).nextLocked(0xc000114580)
	database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
	database/sql/sql.go:2945 +0x2f
database/sql.withLock({0x13a96f8, 0xc0001145b0}, 0xc0006bf470)
	database/sql/sql.go:3396 +0x8c
database/sql.(*Rows).Next(0xc000114580)
	database/sql/sql.go:2944 +0x6f
github.com/jmoiron/sqlx.scanAll({0x13c4318, 0xc000618aa0}, {0xfc6e60, 0xc000789320}, 0x1)
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:950 +0x5a7
github.com/jmoiron/sqlx.StructScan(...)
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:1001
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake.ListSchemas({0xc0004861e0, 0x12}, 0xc00012b7c0)
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake/schema.go:226 +0x147
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/datasources.ReadSchemas(0xc0004a3200, {0x1196de0, 0xc0000b0d00})
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/datasources/schemas.go:54 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x11abfe9, {0x13be5d8, 0xc000489380}, 0xc0006ac450, {0x1196de0, 0xc0000b0d00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000519500, {0x13be5d8, 0xc000489380}, 0xc0004a3100, {0x1196de0, 0xc0000b0d00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:569 +0xf7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00000c180, {0x13be5d8, 0xc000489380}, 0xc00068cb60)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:1133 +0x3a8
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0003d4320, {0x13be680, 0xc0006819b0}, 0xc000682f50)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/tf5server/server.go:657 +0x50b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x11668a0, 0xc0003d4320}, {0x13be680, 0xc0006819b0}, 0xc00068aae0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00007ea80, {0x13d15a8, 0xc00044f6c0}, 0xc0003e8fc0, 0xc0001abfb0, 0x1b73ef0, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00007ea80, {0x13d15a8, 0xc00044f6c0}, 0xc0003e8fc0, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.44.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.44.0/server.go:919 +0x294
Error: The terraform-provider-snowflake_v0.28.6 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by flocknroll** [comment]
Got the same problem with v0.28.6 in a Gitlab runner environment with the hashicorp/terraform:1.1.7 Docker image (based on Alpine linux).
Seems related to https://github.com/snowflakedb/gosnowflake/issues/555.

It looked like a timezone settings issue so I configured the runner following https://wiki.alpinelinux.org/wiki/Setting_the_timezone and it fixed the error.

Hope the workaround can help.

**Comment by daniepett** [comment]
Should've mentioned, I'm also running this in a Gitlab runner setup. The workaround worked for me as well. Thanks!
