### ISSUE TITLE
panic: time: missing Location in call to Time.In

### ISSUE THREAD

**Issue by beparmentier** [chanzuckerberg/terraform-provider-snowflake#934]
**Provider Version**

terraform-provider-snowflake_v0.28.7

**Terraform Version**

v1.1.7

**Describe the bug**

```
Stack trace from the terraform-provider-snowflake_v0.28.7 plugin:

panic: time: missing Location in call to Time.In

goroutine 50 [running]:
time.Time.In(...)
	time/time.go:1106
github.com/snowflakedb/gosnowflake.stringToValue(0xc000505a00, {{0xc000e65bc0, 0xa}, 0x0, 0x0, {0xc000e65bd0, 0xd}, 0x0, 0x3, 0x1}, ...)
	github.com/snowflakedb/gosnowflake@v1.6.7/converter.go:227 +0xe06
github.com/snowflakedb/gosnowflake.(*snowflakeRows).Next(0xc00044b080, {0xc000505a00, 0x8, 0xd})
	github.com/snowflakedb/gosnowflake@v1.6.7/rows.go:173 +0x4b6
github.com/luna-duclos/instrumentedsql.wrappedRows.Next({{{0x139c180, 0xc00032ef70}, {0x139c1e0, 0x1bb6578}, 0x0, 0x0}, {0x13bf7f0, 0xc000048090}, {0x13abeb8, 0xc00044b080}}, ...)
	github.com/luna-duclos/instrumentedsql@v1.1.3/rows.go:52 +0x1e2
database/sql.(*Rows).nextLocked(0xc000505900)
	database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
	database/sql/sql.go:2945 +0x2f
database/sql.withLock({0x13aa858, 0xc000505930}, 0xc00063b2d8)
	database/sql/sql.go:3396 +0x8c
database/sql.(*Rows).Next(0xc000505900)
	database/sql/sql.go:2944 +0x6f
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.readGenericCurrentGrants(0x0, {0x13c5438, 0xc0006d2d50})
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/grant_helpers.go:314 +0x153
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.readGenericGrant(0xc0003b5d00, {0x1197f20, 0xc0003d6b60}, 0x1, {0x13c5438, 0xc0006d2d50}, 0x0, 0x0)
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/grant_helpers.go:206 +0xa5
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.ReadDatabaseGrant(0xc0003b5d00, {0x1197f20, 0xc0003d6b60})
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/database_grant.go:129 +0x2e6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x11ad129, {0x13bf7b8, 0xc0002ea780}, 0x24, {0x1197f20, 0xc0003d6b60})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000451c00, {0x13bf7b8, 0xc0002ea780}, 0xc000388a90, {0x1197f20, 0xc0003d6b60})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00031b1a0, {0x13bf7b8, 0xc0002ea780}, 0xc0002ea800)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000376140, {0x13bf860, 0xc0006d2000}, 0xc0006ce540)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/tf5server/server.go:746 +0x537
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x11679e0, 0xc000376140}, {0x13bf860, 0xc0006d2000}, 0xc0006ce4e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000400a80, {0x13d2788, 0xc0000c61a0}, 0xc000449d40, 0xc00046cc90, 0x1b74e90, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000400a80, {0x13d2788, 0xc0000c61a0}, 0xc000449d40, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.44.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.44.0/server.go:919 +0x294
panic: time: missing Location in call to Time.In

goroutine 32 [running]:
time.Time.In(...)
	time/time.go:1106
github.com/snowflakedb/gosnowflake.stringToValue(0xc000778ab0, {{0xc00077ae30, 0xa}, 0x0, 0x0, {0xc00077ae40, 0xd}, 0x0, 0x3, 0x1}, ...)
	github.com/snowflakedb/gosnowflake@v1.6.7/converter.go:227 +0xe06
github.com/snowflakedb/gosnowflake.(*snowflakeRows).Next(0xc000689620, {0xc000778ab0, 0x9, 0xd})
	github.com/snowflakedb/gosnowflake@v1.6.7/rows.go:173 +0x4b6
github.com/luna-duclos/instrumentedsql.wrappedRows.Next({{{0x139c180, 0xc000326f60}, {0x139c1e0, 0x1bb6578}, 0x0, 0x0}, {0x13bf7f0, 0xc000048090}, {0x13abeb8, 0xc000689620}}, ...)
	github.com/luna-duclos/instrumentedsql@v1.1.3/rows.go:52 +0x1e2
database/sql.(*Rows).nextLocked(0xc000612980)
	database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
	database/sql/sql.go:2945 +0x2f
database/sql.withLock({0x13aa858, 0xc0006129b0}, 0xc000661548)
	database/sql/sql.go:3396 +0x8c
database/sql.(*Rows).Next(0xc000612980)
	database/sql/sql.go:2944 +0x6f
github.com/jmoiron/sqlx.(*Row).Scan(0xc000721f80, {0xc000778990, 0xc000556fc0, 0x9})
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:201 +0xb4
github.com/jmoiron/sqlx.(*Row).scanAny(0xc000721f80, {0xfcfa40, 0xc000556fc0}, 0x1)
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:789 +0x605
github.com/jmoiron/sqlx.(*Row).StructScan(...)
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:794
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake.ScanDatabase(0xc0003cec30)
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake/database.go:93 +0x45
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.ReadDatabase(0xc0000dc000, {0x1197f20, 0xc0003cec30})
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/database.go:152 +0x1bd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x11ad129, {0x13bf7b8, 0xc0003c9e80}, 0x24, {0x1197f20, 0xc0003cec30})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00031bce0, {0x13bf7b8, 0xc0003c9e80}, 0xc0003cfba0, {0x1197f20, 0xc0003cec30})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00030f1b8, {0x13bf7b8, 0xc0003c9e80}, 0xc0003c9f00)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00036c0a0, {0x13bf860, 0xc0003fd7d0}, 0xc000441b00)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/tf5server/server.go:746 +0x537
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x11679e0, 0xc00036c0a0}, {0x13bf860, 0xc0003fd7d0}, 0xc000441aa0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003f8a80, {0x13d2788, 0xc0000ca000}, 0xc00039b8c0, 0xc000464c90, 0x1b74e90, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0003f8a80, {0x13d2788, 0xc0000ca000}, 0xc00039b8c0, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.44.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.44.0/server.go:919 +0x294
panic: time: missing Location in call to Time.In

goroutine 59 [running]:
time.Time.In(...)
	time/time.go:1106
github.com/snowflakedb/gosnowflake.stringToValue(0xc0003d10a0, {{0xc000501c30, 0xa}, 0x0, 0x0, {0xc000501c40, 0xd}, 0x0, 0x3, 0x1}, ...)
	github.com/snowflakedb/gosnowflake@v1.6.7/converter.go:227 +0xe06
github.com/snowflakedb/gosnowflake.(*snowflakeRows).Next(0xc0006e09c0, {0xc0003d10a0, 0x7, 0xd})
	github.com/snowflakedb/gosnowflake@v1.6.7/rows.go:173 +0x4b6
github.com/luna-duclos/instrumentedsql.wrappedRows.Next({{{0x139c180, 0xc00032ef80}, {0x139c1e0, 0x1bb6578}, 0x0, 0x0}, {0x13bf7f0, 0xc000048090}, {0x13abeb8, 0xc0006e09c0}}, ...)
	github.com/luna-duclos/instrumentedsql@v1.1.3/rows.go:52 +0x1e2
database/sql.(*Rows).nextLocked(0xc000512300)
	database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
	database/sql/sql.go:2945 +0x2f
database/sql.withLock({0x13aa858, 0xc000512330}, 0xc00040f478)
	database/sql/sql.go:3396 +0x8c
database/sql.(*Rows).Next(0xc000512300)
	database/sql/sql.go:2944 +0x6f
github.com/jmoiron/sqlx.(*Row).Scan(0xc000806300, {0xc0003d0fc0, 0xc000492840, 0x7})
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:201 +0xb4
github.com/jmoiron/sqlx.(*Row).scanAny(0xc000806300, {0xfcf800, 0xc000492840}, 0x1)
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:789 +0x605
github.com/jmoiron/sqlx.(*Row).StructScan(...)
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:794
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake.ScanMaskingPolicies(0xc0003d8c30)
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake/masking_policy.go:148 +0x45
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.ReadMaskingPolicy(0xc0003b6f00, {0x1197f20, 0xc0003d8c30})
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/masking_policy.go:182 +0x26a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x11ad129, {0x13bf7b8, 0xc0001c90c0}, 0x24, {0x1197f20, 0xc0003d8c30})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00044e1c0, {0x13bf7b8, 0xc0001c90c0}, 0xc0000a5380, {0x1197f20, 0xc0003d8c30})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0003171a0, {0x13bf7b8, 0xc0001c90c0}, 0xc0001c9140)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0003880a0, {0x13bf860, 0xc0002cce40}, 0xc000310cc0)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/tf5server/server.go:746 +0x537
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x11679e0, 0xc0003880a0}, {0x13bf860, 0xc0002cce40}, 0xc000310c60, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000400a80, {0x13d2788, 0xc000455380}, 0xc0002b1e60, 0xc000470c90, 0x1b74e90, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000400a80, {0x13d2788, 0xc000455380}, 0xc0002b1e60, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.44.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.44.0/server.go:919 +0x294

Error: The terraform-provider-snowflake_v0.28.7 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behavior**

Apply the code.

**Code samples and commands**

Just a quick sample of what we add in our existing code 

```terraform
resource snowflake_user "NOR_FI_RH_USER" {
  provider             = snowflake.SECURITYADMIN
  name                 = "NOR_FI_RH_USER"
  login_name           = "NOR_FI_RH_USER"
  comment              = "Technical user"
  disabled             = false
  display_name         = "User for FI and RH Usage"
  email                = "astreinte_pilote@xxx.com"
  default_role         = "NOR_FI_RH"
  must_change_password = false
}
```

**Additional context**

nothing

**Comment by thenaturalist** [comment]
@beparmentier see https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/927 & https://github.com/snowflakedb/gosnowflake/issues/555

**Comment by beparmentier** [comment]
oops sorry for the duplicate, I close it.
