### ISSUE TITLE
terraform plan gets crashed: panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by yohei1126** [chanzuckerberg/terraform-provider-snowflake#949]
**Provider Version**

v0.25.29

**Terraform Version**

Terraform v1.1.7
on darwin_amd64

**Describe the bug**

```
$ terraform plan
...
Stack trace from the terraform-provider-snowflake_v0.25.29 plugin:

panic: runtime error: index out of range [1] with length 0

goroutine 114 [running]:
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.ReadProcedure(0xc00038eb00, {0x1cc88e0, 0xc0004984e0})
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/procedure.go:258 +0x111d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1cdc49c, {0x1ecf378, 0xc000054a00}, 0x24, {0x1cc88e0, 0xc0004984e0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:335 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004e6620, {0x1ecf378, 0xc000054a00}, 0xc0003fcc30, {0x1cc88e0, 0xc0004984e0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:624 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0004a0078, {0x1ecf378, 0xc000054a00}, 0xc000054a40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0002dade0, {0x1ecf420, 0xc00007c450}, 0xc0003b64e0)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:298 +0x1fb
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1c93f60, 0xc0002dade0}, {0x1ecf420, 0xc00007c450}, 0xc0003b6480, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00049c380, {0x1ee1610, 0xc0003d0000}, 0xc0008507e0, 0xc00007cdb0, 0x261aa70, 0x0)
        google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00049c380, {0x1ee1610, 0xc0003d0000}, 0xc0008507e0, 0x0)
        google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.41.0/server.go:921 +0x294

Error: The terraform-provider-snowflake_v0.25.29 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behavior**

terraform plan succeeds

**Code samples and commands**

**Additional context**

* I am deploying the same terraform code to 3 different Snowflake accounts. This issue happen only on a specific account only.
* I am using s3 backend
* Error message in log
```
2022-03-25T14:31:23.984+0800 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-03-25T14:31:23.984+0800 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-03-25T14:31:23.984+0800 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-03-25T14:31:23.984+0800 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-03-25T14:31:23.984+0800 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-03-25T14:31:23.984+0800 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-03-25T14:31:23.984+0800 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-03-25T14:31:23.984+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_def_condition_set_raw" error: Plugin did not respond
2022-03-25T14:31:23.984+0800 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-03-25T14:31:23.984+0800 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-03-25T14:31:23.984+0800 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_def_condition_set_raw" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_date_raw" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_defl_race_raw" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_list_case_status_raw" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_def_condition_set_raw (expand)" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_list_case_status_raw" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_list_case_status_raw (expand)" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_queryviewrsltfldcriteriamap_raw" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.shared.snowflake_procedure.udp_views_validation" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_queryviewrsltfldcriteriamap_raw" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_analy.snowflake_table.lagppf_fpldta_raw" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_analy.snowflake_table.lagppf_fpldta_raw" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_claimltrsetup_raw" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_claimltrsetup_raw" error: Plugin did not respond
2022-03-25T14:31:23.987+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.987+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_claimltrsetup_raw (expand)" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_finauthoritylimit_m_raw" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_finauthoritylimit_m_raw" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_finauthoritylimit_m_raw (expand)" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_sgao.snowflake_table.myaviva_sg_personal_update_submission_raw" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_sgao.snowflake_table.myaviva_sg_personal_update_submission_raw" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_sgao.snowflake_table.myaviva_sg_personal_update_submission_raw (expand)" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_defl_race_raw" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_userrolegroupmap_raw" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.988+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_paneladminfeesurgeondtl_raw" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_queryviewrsltfldcriteriamap_raw (expand)" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_analy.snowflake_table.lagppf_fpldta_raw (expand)" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_fact_disclosure_policycond_raw" error: Plugin did not respond
2022-03-25T14:31:23.988+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.988+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_fact_disclosure_policycond_raw" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_fact_disclosure_policycond_raw (expand)" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_list_search_type_raw" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_list_search_type_raw" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_date_raw" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_list_search_type_raw (expand)" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.989+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.989+0800 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /var/folders/bf/sy6pj4rn48s2d8n7c_j47tth0000gp/T/plugin3889166231: connect: connection refused""
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_date_raw (expand)" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_defl_race_raw (expand)" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_userrolegroupmap_raw" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_tppayerdtl_raw" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.shared.snowflake_procedure.udp_views_validation" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_service_raw" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.landing_sgaisdwh.snowflake_table.dbo_dim_condition_raw" error: Plugin did not respond
2022-03-25T14:31:23.989+0800 [ERROR] vertex "module.landing_sgrcs.snowflake_table.rcs_jobsprivilegemap_raw" error: Plugin did not respond
```

**Comment by yohei1126** [comment]
This issue started after I deployed a stored procedure. after I remove it, the error did not happen.
