### ISSUE TITLE
Plugin crash v0.29.0

### ISSUE THREAD

**Issue by zepomeister** [chanzuckerberg/terraform-provider-snowflake#963]
**My Code  :** 

terraform {
  required_providers {
    snowflake = {
      source = "chanzuckerberg/snowflake"
      version = "0.29.0"
    }
  }
}

resource "snowflake_role" "role" {
  name    = "rking_test_role"
  comment = "for testing"
}

resource "snowflake_role" "role1" {
  name    = "rking_test_role1"
  comment = "for testing"
}

provider "snowflake" {
  account  = var.snowflake_account
  username = var.snowflake_username
  password = var.snowflake_password
}

**Crash  :** 

Stack trace from the terraform-provider-snowflake_v0.29.0.exe plugin:

panic: time: missing Location in call to Time.In

goroutine 29 [running]:
time.Time.In(...)
        time/time.go:1106
github.com/snowflakedb/gosnowflake.stringToValue(0x12a443c0, {{0x126bc830, 0xa}, 0x0, 0x0, {0x126bc840, 0xd}, 0x0, 0x3, 0x1}, ...)
        github.com/snowflakedb/gosnowflake@v1.6.7/converter.go:227 +0x130f
github.com/snowflakedb/gosnowflake.(*snowflakeRows).Next(0x1247c660, {0x12a443c0, 0xa, 0xa})
        github.com/snowflakedb/gosnowflake@v1.6.7/rows.go:173 +0x358
github.com/luna-duclos/instrumentedsql.wrappedRows.Next({{{0xf60998, 0x126dc5a8}, {0xf609d4, 0x162ba0c}, 0x0, 0x0}, {0xf6d104, 0x124a2078}, {0xf6c95c, 0x1247c660}}, ...)
        github.com/luna-duclos/instrumentedsql@v1.1.3/rows.go:52 +0x1af
database/sql.(*Rows).nextLocked(0x12a44280)
        database/sql/sql.go:2967 +0xef
database/sql.(*Rows).Next.func1()
        database/sql/sql.go:2945 +0x2e
database/sql.withLock({0xf6bd3c, 0x12a44298}, 0x127d58d0)
        database/sql/sql.go:3396 +0x57
database/sql.(*Rows).Next(0x12a44280)
        database/sql/sql.go:2944 +0x84
github.com/jmoiron/sqlx.(*Row).Scan(0x1292a168, {0x12a44320, 0xa, 0xa})
        github.com/jmoiron/sqlx@v1.3.4/sqlx.go:201 +0xda
github.com/jmoiron/sqlx.(*Row).scanAny(0x1292a168, {0xbe1080, 0x1292a180}, 0x1)
        github.com/jmoiron/sqlx@v1.3.4/sqlx.go:789 +0x622
github.com/jmoiron/sqlx.(*Row).StructScan(...)
        github.com/jmoiron/sqlx@v1.3.4/sqlx.go:794
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake.ScanRole(0x1292a168)
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake/role.go:23 +0x4b
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.ReadRole(0x127c81e0, {0xd571c0, 0x1280e3f0})
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/role.go:49 +0x142
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.CreateResource.func1(0x127c81e0, {0xd571c0, 0x1280e3f0})
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/resource.go:53 +0x4fe
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.CreateRole(0x127c81e0, {0xd571c0, 0x1280e3f0})
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/role.go:41 +0x8a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1264abd0, {0xf6d0e4, 0x1264d6b0}, 0x127c81e0, {0xd571c0, 0x1280e3f0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x166
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1264abd0, {0xf6d0e4, 0x1264d6b0}, 0x1292ef50, 0x127c80f0, {0xd571c0, 0x1280e3f0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x876
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x125b42d0, {0xf6d0e4, 0x1264d6b0}, 0x1264d710)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xeb4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x125f84b0, {0xf6d144, 0x1256ff38}, 0x12a65dc0)
        github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/tf5server/server.go:812 +0x63f
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd38d20, 0x125f84b0}, {0xf6d144, 0x1256ff38}, 0x1264d230, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x129e8120, {0xf8a5c0, 0x1285a000}, 0x127bd220, 0x12992d98, 0x15fb0a0, 0x0)
        google.golang.org/grpc@v1.44.0/server.go:1282 +0xd5b
google.golang.org/grpc.(*Server).handleStream(0x129e8120, {0xf8a5c0, 0x1285a000}, 0x127bd220, 0x0)
        google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2d
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x126389b0, 0x129e8120, {0xf8a5c0, 0x1285a000}, 0x127bd220)
        google.golang.org/grpc@v1.44.0/server.go:921 +0x92
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.44.0/server.go:919 +0x1a7

Error: The terraform-provider-snowflake_v0.29.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by ptc-olapovsky** [comment]
Hi @zepomeister,
this [solution](https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/945#issuecomment-1077815229)
helped me solve similar problem.
